---
  debug: True
  outfile: "out.csv"
  p1_strategy: q-batch
  p1_cost: 1
  p1_config:
    gamma: 0.8
    p: 0.5
    exploration_type: epsilon-greedy-visit-decay
    explore_config:
      epsilon: 0.99
      decay_lambda: 0.005
    estimate_type: td
    step_type: sample-average
    batch_size: 32
  p0_strategy: custom
  p0_config:
    # dist: [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.0,0.0,0.0,0.0,0.0]
    dist: [0.03,0.04,0.03,0.08,0.12,0.15,0.15,0.08,0.07,0.06,0.06,0.04,0.04,0.03,0.02]
    # dist: [0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1]
    avg_mv: 6.9
    delta: 15
  p0_cost: 1
  duration: 60000
  # rew_type: New_benefit
  rew_type: constant_minus_cost_norm
  rew_config:
    c: 5
  obs_type: opp_LM